// Add more prompts here. Keep each entry in the format:
//   'Piece title - Composer'
// Players only need to guess the title; the composer is shown to the drawer.
module.exports = [
  'Fur Elise - Beethoven',
  'Moonlight Sonata - Beethoven',
  'Ode to Joy - Beethoven',
  'Symphony No 5 - Beethoven',
  'Pathetique Sonata - Beethoven',
  'Waldstein Sonata - Beethoven',
  'Egmont Overture - Beethoven',
  'Violin Concerto in D - Beethoven',
  'Canon in D - Pachelbel',
  'Clair de Lune - Debussy',
  'Arabesque No 1 - Debussy',
  'La Mer - Debussy',
  'Prelude to the Afternoon of a Faun - Debussy',
  'The Four Seasons Spring - Vivaldi',
  'Winter from The Four Seasons - Vivaldi',
  'Concerto for Two Violins in A minor - Vivaldi',
  'Eine kleine Nachtmusik - Mozart',
  'The Magic Flute - Mozart',
  'Piano Concerto No 21 - Mozart',
  'Symphony No 40 - Mozart',
  'Marriage of Figaro Overture - Mozart',
  'Rondo Alla Turca - Mozart',
  'Requiem Lacrimosa - Mozart',
  'Wedding March - Mendelssohn',
  "The Swan - Saint-Saens",
  'Danse Macabre - Saint-Saens',
  'Swan Lake - Tchaikovsky',
  'The Nutcracker - Tchaikovsky',
  'Romeo and Juliet Overture - Tchaikovsky',
  '1812 Overture - Tchaikovsky',
  'Sleeping Beauty Waltz - Tchaikovsky',
  'Air on the G String - Bach',
  'Toccata and Fugue in D Minor - Bach',
  'A Musical Offering - Bach',
  'Brandenburg Concerto - Bach',
  'Cello Suite No 1 Prelude - Bach',
  'Jesu, Joy of Man\'s Desiring - Bach',
  'Goldberg Variations - Bach',
  'Minuet in G Major - Bach',
  'Prelude in C Major - Bach',
  'Etude in D sharp Minor - Scriabin',
  'Hall of the Mountain King - Grieg',
  'Morning Mood - Grieg',
  'Piano Concerto in A Minor - Grieg',
  'Carmen: Habanera - Bizet',
  'Carmen: Toreador Song - Bizet',
  'The Pearl Fishers Duet - Bizet',
  'William Tell Overture - Rossini',
  'The Barber of Seville - Rossini',
  'Hungarian Dance No 5 - Brahms',
  'Lullaby - Brahms',
  'Academic Festival Overture - Brahms',
  'Blue Danube Waltz - Johann Strauss II',
  'Radetzky March - Johann Strauss I',
  'Pizzicato Polka - Johann Strauss II',
  'New World Symphony - Dvorak',
  'Slavonic Dance No 8 - Dvorak',
  'Moldau - Smetana',
  'Pictures at an Exhibition - Mussorgsky',
  'Night on Bald Mountain - Mussorgsky',
  'Flight of the Bumblebee - Rimsky-Korsakov',
  'Scheherazade - Rimsky-Korsakov',
  'Bolero - Ravel',
  'Pavane for a Dead Princess - Ravel',
  'Gymnopedie No 1 - Satie',
  'The Entertainer - Joplin',
  'Maple Leaf Rag - Joplin',
  'Fantaisie Impromptu - Chopin',
  'Nocturne in E flat Major - Chopin',
  'Minute Waltz - Chopin',
  'Polonaise in A flat Major - Chopin',
  'Ballade in G Minor - Chopin',
  'Hungarian Rhapsody No 2 - Liszt',
  'Liebestraum No 3 - Liszt',
  'Ride of the Valkyries - Wagner',
  'Bridal Chorus - Wagner',
  'Meditation from Thais - Massenet',
  'The Planets Jupiter - Holst',
  'The Planets Mars - Holst'
];
